const theme = {
  colors: {
    primary: '#6C63FF',
    primaryDark: '#5A52D5',
    primaryLight: '#8B85FF',
    secondary: '#2D3436',
    success: '#00B894',
    successLight: '#E6F9F3',
    danger: '#E74C3C',
    dangerLight: '#FDECEC',
    warning: '#F39C12',
    warningLight: '#FEF5E7',
    info: '#3498DB',
    infoLight: '#EBF5FB',
    background: '#F5F6FA',
    surface: '#FFFFFF',
    surfaceHover: '#F8F9FD',
    border: '#E1E5EE',
    borderLight: '#F0F2F8',
    text: '#2D3436',
    textSecondary: '#636E72',
    textMuted: '#B2BEC3',
    white: '#FFFFFF',
    shadow: 'rgba(0, 0, 0, 0.08)',
    shadowDark: 'rgba(0, 0, 0, 0.15)',
    overlay: 'rgba(0, 0, 0, 0.5)',
  },
  fonts: {
    primary: "'Poppins', 'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
  },
  radius: {
    sm: '6px',
    md: '10px',
    lg: '16px',
    xl: '20px',
    full: '50%',
  },
  spacing: {
    xs: '4px',
    sm: '8px',
    md: '16px',
    lg: '24px',
    xl: '32px',
    xxl: '48px',
  },
  breakpoints: {
    mobile: '480px',
    tablet: '768px',
    desktop: '1024px',
    wide: '1280px',
  },
  transition: 'all 0.2s ease-in-out',
};

export default theme;
